### ISSUE TITLE
[BUG] The Install link gives a 404

### ISSUE THREAD

**Issue by marcottedan** [League-of-Foundry-Developers/foundryvtt-forien-unidentified-items#7]
**Module Version:** v0.0.0

**Describe the bug**
When you follow the installation steps, this target a 404 module.json. 

I also tried the module.json inside src/ and it has a link to a 404 Manifest as well: 

  "manifest": "https://raw.githubusercontent.com/League-of-Foundry-Developers/foundryvtt-forien-unidentified-items/master/module.json",

**To Reproduce**
1. Inside the Foundry "Configuration and Setup" screen, click "Add-on Modules"
2. Click "Install Module"
3. In the "Manifest URL" field, paste the following url: https://raw.githubusercontent.com/League-of-Foundry-Developers/foundryvtt-forien-unidentified-items/master/module.json

**Expected behavior**
Module should install

**Screenshots**
N/A
**Browser:**
 - 

**Foundry Version:** 
0.8.9

**Game System:** 
dnd 5e latest

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by p4535992** [comment]
Should be solved with this PR https://github.com/League-of-Foundry-Developers/foundryvtt-forien-unidentified-items/pull/8

**Comment by tagnullde** [comment]
Probably related:
Update is still not working.

![grafik](https://user-images.githubusercontent.com/44159008/134151726-813fc2cc-7c0e-4ff2-a714-389b6059ae1b.png)

**Comment by Varriount** [comment]
> 
> 
> Probably related:
> Update is still not working.
> 
> ![grafik](https://user-images.githubusercontent.com/44159008/134151726-813fc2cc-7c0e-4ff2-a714-389b6059ae1b.png)

Is this still happening? What happens if you uninstall the module, then reinstall it (rather than updating)?

**Comment by marcottedan** [comment]
Give me one minute I'm trying it

**Comment by marcottedan** [comment]
Yes it works #1 now, thanks a lot guys!
